server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cvs  # URL de conexión a la base de datos MySQL
    username: root  # Nombre de usuario de la base de datos
    password: gego  # Contraseña de la base de datos
    driver-class-name: com.mysql.cj.jdbc.Driver  # Clase del controlador JDBC para MySQL

  jpa:
    hibernate:
      ddl-auto: update  # Actualiza automáticamente el esquema de la base de datos
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  # Dialecto de Hibernate para MySQL
        
  batch:
    initialize-schema: always
